### ISSUE TITLE
How to add/ remove links from navigation bar

### ISSUE THREAD

**Issue by csethna** [mkchoi212/paper-jekyll-theme#1]
Hi! Thanks for making such a wonderful theme. I am going to be using it for a podcast website. Quick question, I am relatively new to Ruby/ Rails/ Jekyll and I cannot figure out how to add and remove links in the upper navigation bar. The default reads: "Home Projects About RSS." I'm able to create pages by adding new markdown files to the _pages directory, but I am unsure how to alter the navigation bar.

Thanks very much for your help!

**Comment by mkchoi212** [comment]
Thanks @csethna! I believe playing around with https://github.com/mkchoi212/paper-jekyll-theme/blob/2e19509b6beb95f9a8e838c32ad5a95d3108767a/_includes/header.html#L10 should do the trick!
